apiVersion: v1
kind: Service
metadata:
  name: devops-demo-service
  labels:
    app: devops-demo 
spec:
  selector:
    app: devops-demo

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
